# Generated by Django 3.2.9 on 2021-11-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gc',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
