# Generated by Django 3.2.9 on 2021-11-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211110_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2222.22, max_digits=5),
            preserve_default=False,
        ),
    ]
